server {
    listen 80;

    server_name localhost;

    root /app;
    index index.php index.html;

    gzip on;
    gzip_types
        text/plain
        text/css
        application/json
        application/javascript
        text/xml
        application/xml
        application/xml+rss
        text/javascript;

    # Block sensitive files
    location ~ /\.(git|ht) {
        deny all;
        return 404;
    }

    location ~* ^/(composer\.json|composer\.lock|Caddyfile|nginx\.conf|README\.md|README_SOFTDELETE\.md|\.editorconfig)$ {
        deny all;
        return 404;
    }

    # Static files
    location /assets/ {
        try_files $uri =404;
    }

    location /upload/ {
        try_files $uri =404;
    }

    location = /robots.txt {
        try_files $uri =404;
    }

    # Main rewrite
    location / {
        try_files $uri $uri/ /index.php?/$uri&$query_string;
    }

    # PHP-FPM
    location ~ \.php$ {
        include fastcgi_params;

        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;

        fastcgi_index index.php;

        fastcgi_pass app:9000;
    }

    # Deny hidden files
    location ~ /\. {
        deny all;
    }
}